MONGODB_HOST: mongodb.{{ env }}.ahay.space
REDIS_HOST: redis-{{ env }}.ahay.space
CATALOGUE_HOST: catalogue-{{ env }}.ahay.space
CART_HOST: cart-{{ env }}.ahay.space
USER_HOST: user-{{ env }}.ahay.space
RABBITMQ_HOST: rabbitmq-{{ env }}.ahay.space
MYSQL_HOST: mysql-{{ env }}.ahay.space
SHIPPING_HOST: shipping-{{ env }}.ahay.space
PAYMENT_HOST: payment-{{ env }}.ahay.space